name: terraform - test - virtual-network

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - .github/workflows/tf.test.yml
      - .github/workflows/tf.test.azure.virtual-network.yml
      - '*.tf'
      - '*.hcl'
  pull_request:
    branches: [main]
    paths:
      - .github/workflows/tf.test.yml
      - .github/workflows/tf.test.azure.virtual-network.yml
      - '*.tf'
      - '*.hcl'

jobs:
  test:
    uses: ./.github/workflows/tf.test.yml
    with:
      tf_path: azure/virtual-network
      tf_version: latest
    permissions:
      contents: read
      checks: write
      pull-requests: write
